### ISSUE TITLE
You should add .buttonStyle(PlainButtonStyle())

### ISSUE THREAD

**Issue by dimonuch1** [perfaram/TogglableSecureField#1]
You should add .buttonStyle(PlainButtonStyle()) to your cell to avoid unexpected taps on the eye when tapping close to the edges.

**Comment by perfaram** [comment]
Great advice - would you be interested in making a PR for this?

**Comment by dimonuch1** [comment]
It will my first experience with PR, let me a few days
@perfaram

**Comment by perfaram** [comment]
Closed by #2
